---
title: "Using regular expressions"
author: "Peter Clark"
date: "February 8, 2017"
output: html_document
---

####Using Regular expressions

**Problem 1:** The primary reason for using Excel to set up data frames is that people like to have the columns aligned. However, if there are not too many columns, it may be faster to do the job in a plain text editor first and align the columns with tabs. In your text editor, type in (or copy and paste from here) the following lines of text:

```
First String    Second      1.22      3.4
Second          More Text   1.555555  2.2220
Third           x           3         124
```

*Solution*
```
Find: \s{2,}
Replace: ,
```
*find any locations where more than 2 spaces occur. replace with a comma*

Output
```
First String,Second,1.22,3.4
Second,More Text,1.555555,2.2220
Third,x,3,124
```


**Problem 2:** A True Regex Story. I am preparing a collaborative NSF grant with a colleague at another university. One of the pieces of an NSF grant is a listing of potential conflicts of interest. NSF wants to know the first and last name of the collaborator and their institution. Here are a few lines of my conflict list:

```
Ballif, Bryan, University of Vermont
Ellison, Aaron, Harvard Forest
Record, Sydne, Bryn Mawr
```

*Solution*
```
Find: (\w+)\,\s(\w+)\,\s(.*)
Replace: \2 \1 \(\3\)
```
*find first word seperated by a comma and space, then second word seperated by a comma and space, then everything else. To replace, each expression in parenthesis is identifed using a number in its sequence. The find function they calls for the second expression (first nae) to come first, followed by the first expression (last name) then put the third expression (everything else) in parenthesis*

```
Bryan Ballif (University of Vermont)
Aaron Ellison (Harvard Forest)
Sydne Record (Bryn Mawr)
```

**Problem 3:** A Second True Regex Story. A few weeks ago, at Radio Bean’s Sunday afternoon old-time music session, one of the mandolin players gave me a DVD with over 1000 historic recordings of old-time fiddle tunes.
The list of tunes (shown here as a single line of text) looks like this:

```
0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 003 Cherokee Shuffle.mp3 0004 Walking Cane.mp3
```

Unfortunately, in this form, you can’t re-order the file names to put them in alphabetical order. I thought I could just strip out the leading numbers, but this will cause a conflict, because, for wildly popular tunes such as “Shove That Pig’s Foot A Little Further In The Fire”, there are multiple copies somewhere in the list.

All of these files are on a single line, so first write a regular expression to place each file name on its own line:

```
0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Cherokee Shuffle.mp3
0004 Walking Cane.mp3
```

*Solution part 1*
```
Find: mp3 
Replace: mp3\n
```
*find the text "mp3 " (don't forget the space after "mp3") and replace it is mp3 and a new line*

Now write a regular expression to grab the four digit number and put it at the end of the title:

*Solution part 2*
```
Find: (\d{4})\s(.*)\.\mp3
Replace: (\2)_(\1)\.\mp3
```
*select the first for number integers, the space, everything up until the next period. Replace with the second expression folowed by an underscore, then the first expression followed by a .mp3*

```
Georgia Horseshoe_0001.mp3
Billy In The Lowground_0002.mp3
Cherokee Shuffle_0003.mp3
Walking Cane_0004.mp3
```

**Problem 3:** Here is a data frame with genus, species, and two numeric variables.

```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55
```

Write a single regular expression to rearrange the data set like this:

*Solution part 1*
```
Find: (\w)(\w+)\,(\w+),(\d+)\.(\d)\,(\d+)
Replace: (\1)_(\3)\,(\6)
```
*Searches for first letter then remainder of word (genus). Each section is then selected using its on expression. To replace, expression identifiers are called based on their number sequence.*

```
C_pennsylvanicus,44
C_herculeanus,3
M_punctiventris,4
L_neoniger,55
```

Beginning with the original expression, rearrange it to abbreviate the species name like this:

*Solution part 2*
```
Find: (\w{6})(\w+)\,(\d+)
Replace: (\1),(\3)
```
*finds the first four characters in the line and seperates them from the rest ofthe characters to make one expression. The second expression splits the remainder of the species name from the data/integers. replace with only expressions 1 and 3*

```
C_penn,44
C_herc,3
M_punc,4
L_neon,55
```